#!/usr/bin/env bash
# This script display listening ports
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

# netstat -lp
# OR
# netstat -ltup
# OR
# netstat --listening --program
